# https://mise.jdx.dev/configuration.html

[tools]
atuin = "latest"
bat = "latest"
carapace = "latest"
fd = "latest"
fzf = "latest"
jq = "latest"
lsd = "latest"
lua = "latest"
neovim = "latest"
node = "24"
python = "latest"
ripgrep = "latest"
rust = "latest"
sqlite = "latest"
starship = "latest"
stylua = "latest"
tmux = "latest"
vim = "latest"
yazi = "latest"
zoxide = "latest"
